### PR TITLE
Test case now correctly locates DoctrineAnnotations when bundle is in vendor directory

### LINKED ISSUE #97: ESDoctrineTestCase incorrectly locates DoctrineAnnotations.php
When Connections bundle is in vendor directory DoctrineAnnotations.php is not i the place ESDoctrineTestCase expects, thus its impossible to use this test case outside of connections bundle.

### PR DESCRIPTION
**Pull request by GrandLTU**
Closes #97.

### CODE REVIEW

File: Tests/Functional/ESDoctrineTestCase.php [hunk 1]
```diff
@@ -58,9 +58,14 @@ protected function setUp()
     {
         parent::setUp();
 
+        $baseDir = dirname(dirname(__DIR__));
+        if (basename(dirname(dirname($baseDir))) == 'vendor') {
```
Comment (MindaugasR) [inline Tests/Functional/ESDoctrineTestCase.php]: add comments with examples
