### PR TITLE
Fix parameter command

### LINKED ISSUE #104: PairStorage requires strange command format for setting values
working set command looks like this:
`app/console ongr:sync:provide:parameter last_sync_date --set=1 2000-01-01`

--set must equal to 1 otherwise command complains that --set must be used when setting values

### PR DESCRIPTION
**Pull request by trylika**
closes #104

### CODE REVIEW

File: Command/SyncParametersCommand.php [hunk 1]
```diff
@@ -69,11 +63,11 @@ protected function execute(InputInterface $input, OutputInterface $output)
                 ($set_value === null ? 'has no value.' : var_export($set_value, true))
```
Comment (tautrimas) [inline Command/SyncParametersCommand.php]: Should be `$setValue` and can you fix other places where underscore is used in variable names?

Comment (trylika) [inline Command/SyncParametersCommand.php]: ok
